# Generated by Django 4.2.7 on 2024-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutfi', '0002_chatid_alter_kategori_banner_dua_alter_produk_gambar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatid',
            options={'verbose_name_plural': 'Data Chat ID'},
        ),
        migrations.AlterField(
            model_name='produk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
